modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "miningmaster"
version = "${version}"
displayName = "Mining Master"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
enumExtensions="META-INF/enumextensions.json"
#logoFile = ""

[[dependencies.miningmaster]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miningmaster]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miningmaster]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "miningmaster.mixins.json"
